---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.1.0

jobs:
  # IPv6 tests require the machine executor.
  # See https://circleci.com/docs/2.0/faq/#can-i-use-ipv6-in-my-tests for details.
  test:
    machine: true
    working_directory: /home/circleci/.go_workspace/src/github.com/prometheus/blackbox_exporter
    # Whenever the Go version is updated here, .travis.yml and .promu.yml
    # should also be updated.
    environment:
      DOCKER_TEST_IMAGE_NAME: quay.io/prometheus/golang-builder:1.15-base

    steps:
    - checkout
    - run:
        name: enable ipv6
        command: |
          cat \<<'EOF' | sudo tee /etc/docker/daemon.json
          {
            "ipv6": true,
            "fixed-cidr-v6": "2001:db8:1::/64"
          }
          EOF
          sudo service docker restart
    - run: docker run --rm -t -v "$(pwd):/app" "${DOCKER_TEST_IMAGE_NAME}" -i github.com/prometheus/blackbox_exporter -T

workflows:
  version: 2
  blackbox_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - prometheus/build:
        name: build
        filters:
          tags:
            only: /.*/
    - prometheus/publish_master:
        context: org-context
        requires:
        - test
        - build
        filters:
          branches:
            only: master
    - prometheus/publish_release:
        context: org-context
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
